// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: mko_re/gens6/gens6.proto

package gens6pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Services *[]*Service            `protobuf:"bytes,1,rep,name=services"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetServices() []*Service {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *Config) SetServices(v []*Service) {
	x.xxx_hidden_Services = &v
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Services []*Service
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Services = &b.Services
	return m0
}

type Service struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Dependencies []string               `protobuf:"bytes,2,rep,name=dependencies"`
	xxx_hidden_Ready        *ReadyConfig           `protobuf:"bytes,3,opt,name=ready"`
	xxx_hidden_Run          *string                `protobuf:"bytes,4,opt,name=run"`
	xxx_hidden_Finish       *string                `protobuf:"bytes,5,opt,name=finish"`
	xxx_hidden_Down         bool                   `protobuf:"varint,6,opt,name=down"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Service) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Service) GetDependencies() []string {
	if x != nil {
		return x.xxx_hidden_Dependencies
	}
	return nil
}

func (x *Service) GetReady() *ReadyConfig {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return nil
}

func (x *Service) GetRun() string {
	if x != nil {
		if x.xxx_hidden_Run != nil {
			return *x.xxx_hidden_Run
		}
		return ""
	}
	return ""
}

func (x *Service) GetFinish() string {
	if x != nil {
		if x.xxx_hidden_Finish != nil {
			return *x.xxx_hidden_Finish
		}
		return ""
	}
	return ""
}

func (x *Service) GetDown() bool {
	if x != nil {
		return x.xxx_hidden_Down
	}
	return false
}

func (x *Service) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Service) SetDependencies(v []string) {
	x.xxx_hidden_Dependencies = v
}

func (x *Service) SetReady(v *ReadyConfig) {
	x.xxx_hidden_Ready = v
}

func (x *Service) SetRun(v string) {
	x.xxx_hidden_Run = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Service) SetFinish(v string) {
	x.xxx_hidden_Finish = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Service) SetDown(v bool) {
	x.xxx_hidden_Down = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Service) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Service) HasReady() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ready != nil
}

func (x *Service) HasRun() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Service) HasFinish() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Service) HasDown() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Service) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Service) ClearReady() {
	x.xxx_hidden_Ready = nil
}

func (x *Service) ClearRun() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Run = nil
}

func (x *Service) ClearFinish() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Finish = nil
}

func (x *Service) ClearDown() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Down = false
}

type Service_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         *string
	Dependencies []string
	Ready        *ReadyConfig
	Run          *string
	Finish       *string
	Down         *bool
}

func (b0 Service_builder) Build() *Service {
	m0 := &Service{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Dependencies = b.Dependencies
	x.xxx_hidden_Ready = b.Ready
	if b.Run != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Run = b.Run
	}
	if b.Finish != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Finish = b.Finish
	}
	if b.Down != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Down = *b.Down
	}
	return m0
}

type ReadyConfig struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Method isReadyConfig_Method   `protobuf_oneof:"method"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadyConfig) Reset() {
	*x = ReadyConfig{}
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyConfig) ProtoMessage() {}

func (x *ReadyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadyConfig) GetFd() *FileDescriptorReadyConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_Method.(*readyConfig_Fd); ok {
			return x.Fd
		}
	}
	return nil
}

func (x *ReadyConfig) SetFd(v *FileDescriptorReadyConfig) {
	if v == nil {
		x.xxx_hidden_Method = nil
		return
	}
	x.xxx_hidden_Method = &readyConfig_Fd{v}
}

func (x *ReadyConfig) HasMethod() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Method != nil
}

func (x *ReadyConfig) HasFd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Method.(*readyConfig_Fd)
	return ok
}

func (x *ReadyConfig) ClearMethod() {
	x.xxx_hidden_Method = nil
}

func (x *ReadyConfig) ClearFd() {
	if _, ok := x.xxx_hidden_Method.(*readyConfig_Fd); ok {
		x.xxx_hidden_Method = nil
	}
}

const ReadyConfig_Method_not_set_case case_ReadyConfig_Method = 0
const ReadyConfig_Fd_case case_ReadyConfig_Method = 1

func (x *ReadyConfig) WhichMethod() case_ReadyConfig_Method {
	if x == nil {
		return ReadyConfig_Method_not_set_case
	}
	switch x.xxx_hidden_Method.(type) {
	case *readyConfig_Fd:
		return ReadyConfig_Fd_case
	default:
		return ReadyConfig_Method_not_set_case
	}
}

type ReadyConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Method:
	Fd *FileDescriptorReadyConfig
	// -- end of xxx_hidden_Method
}

func (b0 ReadyConfig_builder) Build() *ReadyConfig {
	m0 := &ReadyConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Fd != nil {
		x.xxx_hidden_Method = &readyConfig_Fd{b.Fd}
	}
	return m0
}

type case_ReadyConfig_Method protoreflect.FieldNumber

func (x case_ReadyConfig_Method) String() string {
	md := file_mko_re_gens6_gens6_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isReadyConfig_Method interface {
	isReadyConfig_Method()
}

type readyConfig_Fd struct {
	Fd *FileDescriptorReadyConfig `protobuf:"bytes,1,opt,name=fd,oneof"`
}

func (*readyConfig_Fd) isReadyConfig_Method() {}

type FileDescriptorReadyConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Env         *string                `protobuf:"bytes,1,opt,name=env"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileDescriptorReadyConfig) Reset() {
	*x = FileDescriptorReadyConfig{}
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDescriptorReadyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDescriptorReadyConfig) ProtoMessage() {}

func (x *FileDescriptorReadyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mko_re_gens6_gens6_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileDescriptorReadyConfig) GetEnv() string {
	if x != nil {
		if x.xxx_hidden_Env != nil {
			return *x.xxx_hidden_Env
		}
		return ""
	}
	return ""
}

func (x *FileDescriptorReadyConfig) SetEnv(v string) {
	x.xxx_hidden_Env = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *FileDescriptorReadyConfig) HasEnv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FileDescriptorReadyConfig) ClearEnv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Env = nil
}

type FileDescriptorReadyConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Env *string
}

func (b0 FileDescriptorReadyConfig_builder) Build() *FileDescriptorReadyConfig {
	m0 := &FileDescriptorReadyConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Env != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Env = b.Env
	}
	return m0
}

var File_mko_re_gens6_gens6_proto protoreflect.FileDescriptor

const file_mko_re_gens6_gens6_proto_rawDesc = "" +
	"\n" +
	"\x18mko_re/gens6/gens6.proto\x12\x0fmko_re.gens6.v1\">\n" +
	"\x06Config\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.mko_re.gens6.v1.ServiceR\bservices\"\xb3\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fdependencies\x18\x02 \x03(\tR\fdependencies\x122\n" +
	"\x05ready\x18\x03 \x01(\v2\x1c.mko_re.gens6.v1.ReadyConfigR\x05ready\x12\x10\n" +
	"\x03run\x18\x04 \x01(\tR\x03run\x12\x16\n" +
	"\x06finish\x18\x05 \x01(\tR\x06finish\x12\x12\n" +
	"\x04down\x18\x06 \x01(\bR\x04down\"U\n" +
	"\vReadyConfig\x12<\n" +
	"\x02fd\x18\x01 \x01(\v2*.mko_re.gens6.v1.FileDescriptorReadyConfigH\x00R\x02fdB\b\n" +
	"\x06method\"-\n" +
	"\x19FileDescriptorReadyConfig\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03envB\x1aZ\x18mko.re/gens6/api/gens6pbb\beditionsp\xe8\a"

var file_mko_re_gens6_gens6_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mko_re_gens6_gens6_proto_goTypes = []any{
	(*Config)(nil),                    // 0: mko_re.gens6.v1.Config
	(*Service)(nil),                   // 1: mko_re.gens6.v1.Service
	(*ReadyConfig)(nil),               // 2: mko_re.gens6.v1.ReadyConfig
	(*FileDescriptorReadyConfig)(nil), // 3: mko_re.gens6.v1.FileDescriptorReadyConfig
}
var file_mko_re_gens6_gens6_proto_depIdxs = []int32{
	1, // 0: mko_re.gens6.v1.Config.services:type_name -> mko_re.gens6.v1.Service
	2, // 1: mko_re.gens6.v1.Service.ready:type_name -> mko_re.gens6.v1.ReadyConfig
	3, // 2: mko_re.gens6.v1.ReadyConfig.fd:type_name -> mko_re.gens6.v1.FileDescriptorReadyConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mko_re_gens6_gens6_proto_init() }
func file_mko_re_gens6_gens6_proto_init() {
	if File_mko_re_gens6_gens6_proto != nil {
		return
	}
	file_mko_re_gens6_gens6_proto_msgTypes[2].OneofWrappers = []any{
		(*readyConfig_Fd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mko_re_gens6_gens6_proto_rawDesc), len(file_mko_re_gens6_gens6_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mko_re_gens6_gens6_proto_goTypes,
		DependencyIndexes: file_mko_re_gens6_gens6_proto_depIdxs,
		MessageInfos:      file_mko_re_gens6_gens6_proto_msgTypes,
	}.Build()
	File_mko_re_gens6_gens6_proto = out.File
	file_mko_re_gens6_gens6_proto_goTypes = nil
	file_mko_re_gens6_gens6_proto_depIdxs = nil
}
